version: '3.0'

services:
  api:
    container_name: server
    build:
      context: ./api
    env_file:
      - ./api/.production.env
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 5000:5000
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    depends_on:
      - postgres
    restart: always
  dashboard:
    container_name: client
    build:
      context: ./dashboard
    ports:
      - 8080:8080
    command: npm run start:prod
    depends_on:
      - api
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./api/.production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: